### ISSUE TITLE
Not detecting faces on iOS 14 on an image from imagePicker front camera

### ISSUE THREAD

**Issue by tattivitorino** [bharat-biradar/Google-Ml-Kit-plugin#265]
Hello everyone,
I am having a problem detecting faces on iOS 14 with an image coming from the image picker (source: camera). 
I take the picture with the front camera and start processing to detect faces. I'm using an older version of the ml kit because I can't upgrade my project at the moment. 

Android is working perfectly

The first error that i have is this: (i've researched a bit and appears to be a known iOS 14 issue)

```
[Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}
```
I wonder if this problem is interfering with the processing of the face detector..
here is basically what i do:
```
_faceDetector = GoogleMlKit.vision.faceDetector(
      FaceDetectorOptions(
        mode: FaceDetectorMode.accurate,
      ),
    );
XFile imageFile = await _imagePicker.pickImage(
        source: ImageSource.camera,
        preferredCameraDevice: CameraDevice.front,
      );
final inputImage = InputImage.fromFilePath(imageFile.path);
final faces = await _faceDetector.processImage(inputImage);
```
faces.length is 0.

I've done all settings and configs necessary for iOS, excluding armv7 architecture, changing the pod file, I even added this in the .plist:
```
<key>LSSupportsOpeningDocumentsInPlace</key> 
<true/>
```

My pubspec: (I need the v0.7.3 due to the Flutter version my project is right now!)
```
image_picker: ^0.8.4
google_ml_kit: ^0.7.3
```
Flutter doctor:
```
[✓] Flutter (Channel stable, 2.0.3, on macOS 12.2.1 21D62 darwin-x64, locale en-BR)
    • Flutter version 2.0.3 at /Users/xxx/Tools/flutter
    • Framework revision 4d7946a68d (1 year, 2 months ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device 
    • Iphone 7 Plus (mobile) • • ios            • iOS 14.1

• No issues found!
```

if any of you have any idea on how i can sort this, please let me know
thanks a lot

**Comment by fbernaly** [comment]
@tattivitorino: you need to start using the latest version, in fact you need to stop using `google_ml_kit` and start using `google_mlkit_face_detection` if you intention is only to use Face detection, we wont be able to provide support for an old version when a new one is available. First you need to confirm that issue is reproducible in the latest version and then we can help.

Look at this for why you should start using `google_mlkit_face_detection`: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit

**Comment by fbernaly** [comment]
Also, give our example app a try, so far it is working for iOS: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit/example

**Comment by fbernaly** [comment]
BTW, Did you added this to your `Info.plist`? Even though you are using the image picker you are still using the camera, and therefore you need to add those permission descriptions.

```
<key>NSCameraUsageDescription</key>
<string>your usage description here</string>
<key>NSMicrophoneUsageDescription</key>
<string>your usage description here</string>
```

If that is the case, that is outside the scope of this plugin.

**Comment by tattivitorino** [comment]
@fbernaly thank you so much for your reply! I will discuss with my team the project upgrade as it is long overdue! 
I didnt add the Microphone permission because we're not recording video, but I'll certainly give it a try! And I know we should use the plugins separately because of the increase in the size of the binaries. 
Anyway.. thanks a lot for the help! Cheers

**Comment by tattivitorino** [comment]
@fbernaly 
I setup a simple project using the updated versions of Flutter, FaceDetection, Image Picker and so on.. and I'm still facing the same problem.. see below please! I'm able to convert the XFile into InputImage but processing to detect faces does return faces empty!

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.2.1 21D62 darwin-x64, locale en-BR)
    • Flutter version 2.10.0 at /Users/tattivitorino/Tools/flutter_2100
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (4 months ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tattivitorino/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/tattivitorino/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/tattivitorino/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
My pubspec:
```
name: evom_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  camera: ^0.9.7+1
  google_mlkit_face_detection: ^0.3.0
  path: ^1.8.0
  path_provider: ^2.0.10
  image: ^3.1.3
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
Info.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Evom App</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>evom_app</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>LSSupportsOpeningDocumentsInPlace</key> 
	<true/>
	<key>NSCameraUsageDescription</key>
	<string>Precisamos acessar a câmera para a leitura de QR Code e envio de documentos.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Precisamos acessar sua biblioteca de fotos para o envio de documentos.</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Precisamos acessar o seu microfone para o envio de documentos.</string>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>
```

Podfile

```
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

$iOSVersion = '12.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|

  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=*]"] = "armv7"
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSVersion
  end

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      if Gem::Version.new($iOSVersion) > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSVersion
      end
    end
    
  end
end
```
XCode Build Settings:
![image](https://user-images.githubusercontent.com/5480296/171048489-aaf22e0b-98cf-435f-9f70-8c223e6a9f28.png)

main.dart
```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:google_mlkit_face_detection/google_mlkit_face_detection.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final FaceDetector _faceDetector = FaceDetector(
    options: FaceDetectorOptions(),
  );

  ImagePicker _imagePicker = ImagePicker();
  XFile? _imageFile;
  List<Face>? _faces;

  bool _isLoading = false;
  bool _isProcessing = false;

  String _error = '';

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    _faceDetector.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: _buildBody(),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }

  _buildBody() {
    final wWidth = MediaQuery.of(context).size.width;
    final wHeight = MediaQuery.of(context).size.height;
    if (_isLoading) {
      return const Center(
        child: Text('Carregando!'),
      );
    }
    if (_imageFile == null) {
      return Center(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('Abra a camera para tirar uma foto!'),
            const SizedBox(height: 16),
            IconButton(
              onPressed: _getImageAndDetectFaces,
              icon: const Icon(Icons.add_a_photo),
            ),
          ],
        ),
      );
    }
    return Stack(
      fit: StackFit.expand,
      children: [
        ListView(
          children: [
            if (_imageFile != null) ...[
              Container(
                alignment: Alignment.center,
                child: const Text('Imagem Original'),
              ),
              const SizedBox(
                height: 8,
              ),
              Container(
                alignment: Alignment.center,
                child: Image.file(File(_imageFile!.path), width: wWidth * 0.5),
              ),
            ],
            const SizedBox(
              height: 16,
            ),
            if (_isProcessing) ...[
              Container(
                alignment: Alignment.center,
                child: const Text('Processando a imagem...'),
              ),
              const SizedBox(
                height: 8,
              ),
              Container(
                alignment: Alignment.center,
                child: const Text('Carregando...'),
              ),
            ],
            const SizedBox(
              height: 16,
            ),
            if (_error != null) ...[
              Container(
                alignment: Alignment.center,
                child: Text('$_error'),
              ),
            ],
          ],
        ),
        Positioned(
          bottom: 10,
          right: 10,
          child: IconButton(
            onPressed: _reset,
            icon: const Icon(Icons.refresh),
          ),
        ),
      ],
    );
  }

  _getImageAndDetectFaces() async {
    try {
      var imageFile = await _imagePicker.pickImage(
        source: ImageSource.camera,
        preferredCameraDevice: CameraDevice.front,
      );
      if (imageFile == null) return;
      setState(() {
        _isLoading = true;
      });

      print('IMAGE FILE: ${imageFile.path} - ${imageFile.mimeType}');

      setState(() {
        _isLoading = false;
        _isProcessing = true;
        _imageFile = imageFile;
      });

      final inputImage = InputImage.fromFilePath(imageFile.path);
      print(
          'INPUT IMAGE PROCESSED: ${inputImage.filePath} - ${inputImage.type}');

      final faces = await _faceDetector.processImage(inputImage);
      print('Found ${faces.length} faces for picked file');
      if (faces.isEmpty) {
        setState(() {
          _isLoading = false;
          _isProcessing = false;
        });
        throw Exception('Nenhum rosto foi detectado na imagem!');
      }
    } catch (e) {
      setState(() {
        _isLoading = false;
        _isProcessing = false;
        _error = 'ERRO PROCESSANDO A IMAGEM:\n$e';
      });
    }
  }

  _reset() {
    setState(() {
      _imageFile = null;
      _faces?.clear();

      _isLoading = false;
      _isProcessing = false;

      _error = '';
    });
  }
}
```
Console logs
```
[Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}

flutter: IMAGE PICKER FILE: /private/var/mobile/Containers/Data/Application/79D03D14-1FAE-497D-817B-462D84769ED8/tmp/image_picker_E20987F1-8D6F-4511-B0F0-013DEAB35544-8818-00001170D4F6EDE7.jpg - null
flutter: ML KIT INPUT IMAGE PROCESSED: /private/var/mobile/Containers/Data/Application/79D03D14-1FAE-497D-817B-462D84769ED8/tmp/image_picker_E20987F1-8D6F-4511-B0F0-013DEAB35544-8818-00001170D4F6EDE7.jpg - InputImageType.file

2022-05-30 15:58:40.545 Runner[8818/0x101a8b880] [lvl=3] +[MLKITx_CCTClearcutUploader crashIfNecessary] Multiple instances of CCTClearcutUploader were instantiated. Multiple uploaders function correctly but have an adverse affect on battery performance due to lock contention.

Initialized TensorFlow Lite runtime.

INFO: Initialized TensorFlow Lite runtime.

[WARNING]The specified colorspace format is not supported. Falling back on Libyuv.

flutter: Found 0 faces for picked file
```
